spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/nairacore
    username: nairacore
    password: nairacore

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  mail:
    host: mailpit
    port: 1025

  jpa:
    show-sql: false